language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
script: python setup.py test
install:
    python setup.py install
before_script:
    - if [[ $TRAVIS_PYTHON_VERSION == '3'* ]]; then 2to3 --write --nobackups .; fi
